### ISSUE TITLE
Error building 32 bit Python binding for Windows

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/libSBOL#191]
When building 32bit Python version on Windows, following error occurs.
```
error C4716: 'new_sbol_EnzymeCatalysisInteraction__SWIG_3': must return a value
error C4716: 'new_sbol_EnzymeCatalysisInteraction__SWIG_4': must return a value
````
This can be probably avoided by adding some return call in [libsbol.i](https://github.com/SynBioDex/libSBOL/blob/master/wrapper/libsbol.i#L1125-L1144)

**Comment by kirichoi** [comment]
@bbartley: Please check that the solution in commit e1ce2dc1b1c7cff6099c04f04771e1966da26493 is okay. I believe the function does not need to return anything.

**Comment by bbartley** [comment]
Fixed by 877c9aa4238d306da261b6b629c851053c1e9faa

SWIG has kind of a weird pattern for implementing alternative constructors.  In C++ typically a constructor does not have a return value, but in SWIG the constructor must return a pointer to the new object.  See https://stackoverflow.com/questions/33564645/how-to-add-an-alternative-constructor-to-the-target-language-specifically-pytho

**Comment by kirichoi** [comment]
Interesting. Let me quickly check that it works on Windows and I will close the issue. Do you want this to be merged to master right now? (with updated release?)

**Comment by bbartley** [comment]
Its probably not worth the trouble of tagging a new release, since this only affects the Python bindings.  To save yourself the headache, I'd recommend just building the Python packages off the develop branch.
B
