### ISSUE TITLE
Perform automated cross-validation on SBOL test-suite.

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/libSBOL#32]
Test files for cross-validation are found in the SynBioDex/SBOLTestSuite repository.

**Comment by bbartley** [comment]
Cross-validation suite and Restbed have been integrated with libSBOL, but still need to implement RESTful queries of the online validator tool.

**Comment by kirichoi** [comment]
This is temporarily suspended.

**Comment by bbartley** [comment]
@kirichoi  Can you test on Windows?  Specify SBOL_BUILD_TESTS=TRUE to build the test application sbol_test in libsbol/test.  Running the test application should iterate through test files.

**Comment by kirichoi** [comment]
Windows build process fails with several errors. First of all, Windows does not have unistd.
Regardless, there are some unresolved external symbols.

**Comment by bbartley** [comment]
Hmm.  At one time this worked on Windows.  It may be possible to get newer Windows versions of the dirent.h header.  This header is default system header on Linux/Mac and there are well-supported Windows sources online.

**Comment by kirichoi** [comment]
The problem comes from the fact that sbol_test target is not fully configured. It does not add any information on additional libraries or include folder, which is necessary on windows. Fixing this results proper compilation, but I cannot find there the executable is located at :S 
Here are the changes that needs to be made:
1. change `#include <dirent.h>` to `#include "dirent.h"`
2. remove `#include <unistd.h>` or use conditionally. (I.e. ifdef WIN32)
3. Update CMakeLists to automatically populate paths for additional libraries and include folder. Also add library names for linker input. Use install path for this for it will have all the libraries, etc.
4. Actually install target under installpath/bin

**Comment by kirichoi** [comment]
Checked the executable and it works fine. Fixed 1. and 2. through commit 8ccf6b2be0abde8156f82e7a8913202af75e2282.

**Comment by kirichoi** [comment]
Fixed 3. and 4. through commit 90b00daaa9e086c61cd73abbbdb6503bef877c07.
Building test suite in Windows fully functional.

**Comment by bbartley** [comment]
Spectacular! =)
