### ISSUE TITLE
Example script no longer works

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/libSBOL#71]
Example script that assembles sequence (e.g. SequenceAssemblyExample.cpp) no longer works, at least in Python bindings. The error is:

`AttributeError: 'NoneType' object has no attribute 'identity'`

`SBOL error 1:Object http://sys-bio.org/ComponentDefinition/BB0001/http://sys-bio.org/ComponentDefinition/BB0001/E0040/1.0.0/1.0.0 not found`

Which is caused by
`print(last.identity.get())`

This is due to `last = gene.getLastComponent()` being empty. I suspect bug in the source code.

**Comment by bbartley** [comment]
The object can't be found because the URI is malformed:
http://sys-bio.org/ComponentDefinition/BB0001/http://sys-bio.org/ComponentDefinition/BB0001/E0040/1.0.0/1.0.0 not found

Due to changes in:    template <class SBOLClass>    SBOLClass& OwnedObject<SBOLClass>::operator[] (std::string uri)
I can probably fix this fairly quickly.
